"""
Synthesis Agent
---------------
Merges findings from all specialist agents, deduplicates,
assigns overall severity, and formats the final GitHub comment.
"""
from core.state import AgentState

SEVERITY_ORDER = {"critical": 0, "major": 1, "minor": 2, "info": 3}


def synthesis_node(state: AgentState) -> AgentState:
    """Merge all agent findings into one structured review."""
    all_findings = []

    for source in ["code_review", "security_scan", "test_analysis"]:
        data = state.get(source) or {}
        for f in data.get("findings", []):
            all_findings.append({**f, "_source": source})

    # Deduplicate by (file, line, message prefix)
    seen = set()
    unique = []
    for f in all_findings:
        key = (f.get("file"), f.get("line"), f.get("message", "")[:40])
        if key not in seen:
            seen.add(key)
            unique.append(f)

    # Sort: critical first, then by confidence desc
    unique.sort(key=lambda f: (
        SEVERITY_ORDER.get(f.get("severity", "info"), 9),
        -f.get("confidence", 0),
    ))

    needs_human = [f for f in unique if f.get("needs_human_review")]
    auto_post   = [f for f in unique if not f.get("needs_human_review")]

    # Overall verdict
    severities = [f.get("severity") for f in auto_post]
    if "critical" in severities:
        verdict = "❌ Changes requested — critical issues found"
    elif "major" in severities:
        verdict = "⚠️ Changes requested — major issues found"
    elif auto_post:
        verdict = "💡 Approved with suggestions"
    else:
        verdict = "✅ Looks good — no issues found"

    final_review = {
        "verdict":      verdict,
        "auto_post":    auto_post,
        "needs_human":  needs_human,
        "agents_run":   state.get("tasks", []),
        "errors":       state.get("errors", []),
        "comment_body": _format_comment(verdict, auto_post, needs_human, state),
    }

    return {**state, "final_review": final_review}


def _format_comment(verdict: str, findings: list, low_conf: list, state: AgentState) -> str:
    lines = [
        "## 🤖 AgentOps Review",
        "",
        f"**{verdict}**",
        "",
        f"_Agents run: {', '.join(state.get('tasks', []))}_",
        "",
    ]

    if findings:
        lines += ["### Findings", ""]
        for f in findings:
            sev_icon = {"critical": "🔴", "major": "🟠", "minor": "🟡", "info": "🔵"}.get(f.get("severity"), "⚪")
            file_ref = f"`{f.get('file', 'unknown')}`"
            if f.get("line"):
                file_ref += f" line {f['line']}"
            lines.append(f"{sev_icon} **{f.get('severity', '').upper()}** — {file_ref}")
            lines.append(f"> {f.get('message', '')}")
            lines.append(f"💡 *{f.get('suggestion', '')}*")
            conf = f.get("confidence", 0)
            lines.append(f"<sub>Confidence: {conf:.0%} · Source: {f.get('_source', 'unknown')}</sub>")
            lines.append("")

    if low_conf:
        lines += [
            "---",
            f"### ⚠️ {len(low_conf)} finding(s) flagged for human review",
            "_Low confidence — please verify before acting on these:_",
            "",
        ]
        for f in low_conf:
            lines.append(f"- `{f.get('file', '?')}`: {f.get('message', '')} _(confidence: {f.get('confidence', 0):.0%})_")
        lines.append("")

    if state.get("errors"):
        lines += ["---", "_⚠️ Some agents encountered errors during this review._"]

    lines.append("---")
    lines.append("<sub>Generated by [AgentOps](https://github.com/your-username/agentops)</sub>")

    return "\n".join(lines)
